<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - Ibrat Generator</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="icon" href="/favicon/favicon.ico" type="image/x-icon" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            font-size: 14px;
            color: #333;
            margin: 0;
            background: #f8fafc;
          }
          a {
            color: #1a1a1a;
            text-decoration: none;
            font-weight: 600;
          }
          a:hover {
            text-decoration: underline;
            color: #000;
          }
          .header {
            background: #000;
            color: #fff;
            padding: 40px 20px;
            text-align: center;
          }
          .header h1 {
            margin: 0;
            font-size: 28px;
            letter-spacing: -0.02em;
          }
          .header p {
            margin: 10px 0 0;
            opacity: 0.7;
            font-size: 16px;
          }
          .content {
            max-width: 1000px;
            margin: -40px auto 40px;
            background: #fff;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
            overflow: hidden;
            padding: 20px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
          }
          th {
            text-align: left;
            padding: 15px;
            border-bottom: 2px solid #CCFF00;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            color: #666;
          }
          td {
            padding: 15px;
            border-bottom: 1px solid #f1f5f9;
            word-break: break-all;
          }
          tr:hover td {
            background: #fdfdfd;
          }
          .footer {
            text-align: center;
            padding: 20px;
            color: #94a3b8;
            font-size: 12px;
          }
          .priority-high { color: #059669; font-weight: bold; }
          .priority-med { color: #0891b2; }
          .priority-low { color: #64748b; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Ibrat Generator Sitemap</h1>
          <p>Total URLs: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></p>
        </div>
        <div class="content">
          <table>
            <thead>
              <tr>
                <th width="70%">URL</th>
                <th width="10%">Priority</th>
                <th width="10%">Changefreq</th>
                <th width="10%">Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <xsl:variable name="itemURL">
                      <xsl:value-of select="sitemap:loc"/>
                    </xsl:variable>
                    <a href="{$itemURL}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td>
                    <xsl:variable name="priority" select="sitemap:priority"/>
                    <span>
                      <xsl:attribute name="class">
                        <xsl:choose>
                          <xsl:when test="$priority &gt;= 0.8">priority-high</xsl:when>
                          <xsl:when test="$priority &gt;= 0.5">priority-med</xsl:when>
                          <xsl:otherwise>priority-low</xsl:otherwise>
                        </xsl:choose>
                      </xsl:attribute>
                      <xsl:value-of select="sitemap:priority"/>
                    </span>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:changefreq"/>
                  </td>
                  <td>
                    <xsl:value-of select="substring(sitemap:lastmod, 0, 11)"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
        <div class="footer">
          Generated by Ibrat Generator XML Sitemap Engine
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
